#!/bin/zsh

# plugins=(git osx zsh-autosuggestions vi-mode kubectl zsh-syntax-highlighting z)
plugins=(
	git
	git-flow
	git-flow-avh
	git-hubflow
	git-prompt
	git-remote-branch
	gitfast
	github
	zsh-autosuggestions
#	vi-mode
#	kubectl
	zsh-syntax-highlighting
)

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

HISTSIZE=99999999
SAVEHIST=99999999

# ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME="spaceship"

POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_HOST_TEMPLATE="%2m"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="$ "
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_VI_COMMAND_MODE_STRING=""
POWERLEVEL9K_VI_INSERT_MODE_STRING=""
POWERLEVEL9K_CHRUBY_SHOW_ENGINE=false
POWERLEVEL9K_CHRUBY_SHOW_DEFAULT=false

POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-tagname)
POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_CONTEXT_FOREGROUND='yellow'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='blue'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh vi_mode context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs_joined)

ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='standout'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=50
ZSH_AUTOSUGGEST_USE_ASYNC=1

setopt inc_append_history
setopt correct
setopt extended_history
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_ignore_space

unsetopt nomatch
unsetopt share_history
unsetopt correct
unsetopt correct_all

bindkey -v # vi-mode
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward

export KEYTIMEOUT=1

# additional files to source
for file in ~/.my_{aliases,paths,nvm,pyenv,sw042,exports}; do
    [ -r "$file" ] && source "$file"
done
unset file

# TODO: check https://github.com/lanej/dotfiles/blob/master/sh/alias
# TODO: check for: autoload -U +X bashcompinit && bashcompinit
